.circleci/config.yml
requirements.txt
tests/test_functions.py
tsdate/__init__.py
tsdate/date.py

And add the right priors for missing data

Take find_node_tip_weights out of prior_maker

---

tsdate/date.py

As mentioned in https://github.com/awohns/tsdate/pull/31#issuecomment-535503171

Make tau_var faster for i==n

---

tests/test_functions.py
tsdate/date.py

@awohns - this is quite a bit of extra hacking on your precalculated prior code. Please check it out

Create bespoke precalculated priors & test

---

docs/Makefile
docs/conf.py
docs/index.rst

Also allow compilation of docs using `python3 -m sphinx` and add in links to issues, and add a make clean for docs

Add possibility of linking to tskit in docs

---

tests/test_functions.py
tsdate/__init__.py
tsdate/date.py

And make find_node_tips into a class.
There is some substantial renaming going on here. I hope that's OK @awohns . Do suggest better names for functions and classes if you can think of any.

Put all the prior dataframes into a single obj

---

tests/test_functions.py
tsdate/date.py

This solves most of #48 apart from the hashing of mixtures

Make node weights into np arrays

---

tests/test_functions.py
tsdate/date.py

Allow sample sets to be passed in to functions

---

tests/test_functions.py
tests/test_inference.py
tsdate/date.py

For discussion and testing. This isn't fully tested / optimised yet, but does pass all the existing tests.

Update node weight priors incrementally

---

evaluation/evaluation.py
tests/test_functions.py
tsdate/__init__.py
tsdate/date.py

Rewrote the forward and backward algorithm to purely use 1 dimensional version of lower triangular matrix. Massively increases speed of this part of tsdate.

Optimising the forward and backward algorithms, adding LowerTriangularMatrix class

---

tsdate/date.py

I'm not being stupid here am I @awohns ? It looks like you don't need to save the normalising constants, but can just normalise them on assignment like the attached. Tests all pass...

Remove separate norm constants

---

tests/test_functions.py
tsdate/__init__.py
tsdate/date.py

And don't bother calculating a full lower tri matrix for fixed nodes.
Also put upward/downward in a class of their own, to keep a handle on node mappings etc.

Only store hidden states for unknown nodes

---

evaluation/evaluation.py
requirements.txt
tests/test_functions.py
tests/test_inference.py
tests/utility_functions.py
tsdate/date.py

The internal workings of the algorithm are always in log-space to prevent overflow. This leads to ~2x performance slowdown but now we can work with 1000G-level datasets.

Full logarithmic approach

---

evaluation/evaluation.py
tests/test_functions.py
tests/utility_functions.py
tsdate/__init__.py
tsdate/date.py

Merged lognorm and hyanwong:log-and-linear branches into lognorm. Now merging into master

Lognormal, probability_space framework, correct logic, more tests

---

tests/test_functions.py
tests/utility_functions.py
tsdate/__init__.py
tsdate/date.py

This has the code that can switch between log and linear space (e.g. by uncommenting line 1839). Log space doesn't work at the moment, but all the framework is there. The `outside_maximization` and posterior calcs are not working either, at a guess. Finally, the assert on line 1557 is failing, and I dan't have time to investigate why. I also haven't tested this, apart from to see that it passes `nosetests tests/test_inference.py:TestSimulated.test_simple_sim_1_tree`, so I guess it's not quite ready for merging. 
Could you have a play, @awohns , and see if what I have done seems sensible, though?

Log and linear

---

tests/test_functions.py
tsdate/date.py

Properly calculate and test likelihood functions with threads

---

setup.py
tests/test_functions.py
tests/test_inference.py
tsdate/date.py

Bomb out if dangling nodes, and warn if unary nodes present

---

tsdate/date.py

Not passing because it looks like we might need to create the cache dir if it doesn't already exist?

Caching issue

---

tsdate/date.py

This corrects my previous mistake (simplify() can re-order the node numbers, even if everything else is unchanged)

Properly detect dangling / unary nodes

---

tests/test_functions.py
tests/utility_functions.py
tsdate/date.py

Change the node ordering in the outside pass and outside maximization algorithms. Add an example tree where this is an issue as well as a simulation/inference check.

Correct outside traversal

---

tests/test_cache.py
tests/test_functions.py
tests/test_inference.py
tsdate/base.py
tsdate/date.py
tsdate/prior.py
tsdate/util.py

And rename most examples of "prior" to "priors" to avoid conflict with prior.py

Separate code into different files

---

docs/tutorial.rst
tsdate/date.py
tsdate/provenance.py
tsdate/util.py

Add provenance to tree sequences dated with tsdate (as well as tree sequences which were preprocessed)
Fixes #99

Add provenance to tsdate

---

tsdate/date.py
tsdate/util.py

Now we have this in tskit, we should use it!

Use tskit default edge span method

---

tests/test_functions.py
tests/utility_functions.py
tsdate/util.py

change assert to raise ValueError

---

.flake8
.pre-commit-config.yaml
docs/conf.py
evaluation/evaluate_accuracy.py
requirements.txt
setup.py
tests/test_cache.py
tests/test_cli.py
tests/test_functions.py
tests/test_inference.py
tests/utility_functions.py
tsdate/__init__.py
tsdate/base.py
tsdate/cache.py
tsdate/cli.py
tsdate/date.py
tsdate/prior.py
tsdate/provenance.py
tsdate/util.py

I've done this all as one PR - let me know if you would prefer it split. Most of the changes are from `black`. 
Partly addresses #139

Apply standard tskit-dev pre-commit

---

.github/workflows/docker/buildwheel.sh
.github/workflows/docker/shared.env
.github/workflows/wheels.yml

Production deploy won't work until the right PyPi creds are in place. I've sent you a message about this @awohns.

Build wheels

---

tests/test_functions.py
tsdate/date.py

The current implementation "log-sum-exp" in the `LogLikelihoods` class caused underflow in extreme cases on a few human chromosomes. This is because we simply bring the log values into linear space to sum them: the naive implementation of log-sum-exp.
This PR simply changes to using the "streaming'" version of log-sum-exp that was also implemented but unused

Address underflow in log-sum-exp

---

tsdate/date.py

Following the [note from numba](https://numba.pydata.org/numba-doc/dev/reference/deprecation.html), will close #174

fix numba deprecation

---

docs/introduction.rst
docs/python-api.rst

add citation information to documentation

---

.github/workflows/wheels.yml
requirements.txt
tests/test_functions.py
tests/test_inference.py

(edges are not longer an attrs instance)
This allows tests to pass again

Use new append functionality

---

docs/conf.py
tests/test_inference.py
tsdate/core.py
tsdate/prior.py

Fixes https://github.com/tskit-dev/tsdate/issues/190 and  https://github.com/tskit-dev/tsdate/issues/189

Return posterior and set time_units

---

tsdate/prior.py

It is sometimes useful to make priors etc with unary nodes, even if it's not the best way to run tsdate. This should allow the user to override the current behaviour of always raising an error

Allow unary nodes (not default) when creating prior

---

tsdate/prior.py

Remove noop

---

docs/tutorial.rst

Prompted by a question from @gregorgorjanc

Describe the actual time values

---

requirements.txt

So that we get the root-splitting behaviour

Require newer tsinfer version

---

CHANGELOG.rst
tests/test_functions.py
tests/utility_functions.py
tsdate/util.py

Default to not filtering sites, pops, indivs in preprocess

---

tests/test_functions.py

Since we now have an (undocumented) function to allow unary nodes

Reinstate unary node tests

---

CHANGELOG.rst
tests/test_functions.py
tsdate/base.py
tsdate/core.py
tsdate/prior.py

Is this better @nspope (c.f. https://github.com/tskit-dev/tsdate/pull/232#issuecomment-1381958466 with which I agree)

Change "normalize" to "standardize"

---

tsdate/core.py

To reflect that we are actually calculating likelihood ratios here (dividing in linear space).
Any comments on this terminology @nspope or @awohns ?

Rename "reduce" to "ratio"

---

requirements.txt
tests/test_cli.py
tests/test_functions.py

Tidy tests and unpin numba

---

tsdate/core.py

Better drop-in in replacements for `get_mut_edges` and `edges_by_child_desc`

Some simpler functions

---

tests/test_cli.py
tsdate/cli.py
tsdate/core.py

Output number of iterations using EP

---

CHANGELOG.rst
tests/test_cli.py
tsdate/cli.py
tsdate/prior.py

Change verbosity to a count

---

tsdate/cache.py

Remove unused code in cache.py

---

tests/test_functions.py
tsdate/base.py

And test the probability space conversion more

Raise errors not warnings if we can't convert a probability space

---

.circleci/config.yml

By my reading, this should fix #266

Disable JIT for coverage

---

tests/test_functions.py
tests/test_provenance.py
tsdate/core.py
tsdate/demography.py

Save PopulationSizeHistory params

---

tests/test_functions.py
tsdate/core.py

Fix constrain_ages_topo bug

---

tsdate/core.py
tsdate/prior.py

Hopefully gives a nicer output in notebooks. Fixes #101

Switch to auto tqdm

---

tests/test_cli.py
tsdate/core.py

Make nicer progress bars for iteration

---

.github/workflows/wheels.yml

I've tested the wheel build and test, works now.

Download correct artefact

---

docs/historical_samples.md
docs/introduction.md
docs/usage.md
docs/variable_popsize.md

And explain the posterior DF better

Correct a few more typos

---

docs/methods.md
docs/priors.md
docs/python-api.md
docs/usage.md

And fix some refs. Also add a TODO re numerical instability in the vgamma method

Properly describe "loopy belief propagation"

---

tsdate/core.py

Rather than setting self.epsilon, as it could be used differently in different places
Also shorten some variable names / logic

Pass epsilon explicitly

---

CHANGELOG.md

Needs merging just before release, and release date checked.

Tidy CHANGELOG for 0.1.6

---

tsdate/core.py

Rather than maintain separate scaling factors and unconstrained messages across iterations, absorb the scale into the message at the end of each iteration. The scaling terms are essentially responsible for keeping the posterior shape parameters within a reasonable bound. 
If the scale is never reset, it'll go towards 0 as iterations progress while the (unconstrained) message goes towards infinity. This can underflow and trigger an assert, if the algo is run long enough and a node shows up across a ton of updates (e.g. has an exceptionally long span and/or is involved in large polytomies).

Rescale messages at end of each iteration

---

setup.cfg

Change URL to docs

---

docs/variable_popsize.md

It's causing the docs to time out sometimes

Make the doc example smaller

---

docs/_config.yml

I can't get this to fail like #364, but have extended the timeout anyway.

Extend jupyterbook timeout

---

tests/test_approximations.py
tests/test_functions.py
tests/test_hypergeo.py
tests/test_inference.py
tsdate/approx.py
tsdate/core.py
tsdate/hypergeo.py
tsdate/mixture.py
tsdate/util.py
tsdate/variational.py

- Make the `ExpectationPropagation` class a bit more stand-alone
- Add argument `constraints` to the class, that are lower/upper age bounds per node. If these are equal, the node age is fixed to a particular timepoint. If these are (0, inf) the node age is unconstrained. 
- Add machinery for updating edges where one of the nodes is fixed.
- Some numerical fixes
- Utilities for cutting up nodes

Non-contemporary samples

---

.github/workflows/wheels.yml

Allow compilation of wheels on mac

---

CHANGELOG.md
tsdate/cli.py

Fixes https://github.com/tskit-dev/tsdate/issues/262

Remove "ignore-oldest" option from the CLI

---

tests/test_cli.py
tests/test_inference.py
tsdate/core.py

Fail vgamma if no mutations

---

tests/test_util.py
tsdate/util.py
tsdate/variational.py

It'd be good to get this in before release @hyanwong

Add check for unary nodes

---

docs/methods.md
docs/popsize.md
docs/usage.md

Ping @nspope in case he has nicer wording

Fill out more rescaling explanation

---

tsdate/variational.py

Add note on mutational posteriors for unphased singletons

---

docs/methods.md

Clarify vgamma not strongly dependent on e.g. coalescent assumptions

---

tsdate/core.py
tsdate/variational.py

Fixes 447. I also made sure we weren't specifying defaults in 2 different places. I think this is OK, right, @nspope ?

Change the default number of ep_iterations to 25

---

tsdate/core.py

We missed these off by mistake

Add documented params for variational_gamma

---

.github/workflows/docs.yml

Add merge_group trigger to workflows for GitHub merge queue functionality.

Add merge_group trigger to GitHub Actions workflows
