tskit-dev/tsdate

tsdate/date.py

I assume this should create identical results. Since it's the innermost loop, I'm hoping it will speed things up a bit (e.g. the initial make_prior), although this is another possibility for caching too.
Do the unit tests now include a simple testcase to check inference accuracy doesn't change?

Replace inner make_prior loop with np version

---

tests/test_functions.py
tsdate/__init__.py
tsdate/date.py

I've rewritten the forward algorithm to remove a for loop over hidden states (times). Instead, we just perform the `np.sum() `on all hidden states at once for each child edge.
I've also memoized `get_mixture_prior()`, so that we only calculate the gamma approximation of the mixture if we have not seen that mixture before. However, this involves making a string out of the nested dictionaries of mixtures, which isn't optimal.
More test cases were added for various functions as well.

Optimise forward algorithm and mixture prior; added more unittests

---

tests/test_functions.py
tests/utility_functions.py
tsdate/__init__.py
tsdate/date.py

This seems to pass the test but still complains about "date.py:1079: RuntimeWarning: divide by zero encountered in log  log_backwards = np.log(backwards)" - it might do some more than it used to, as I removed some of the (probably needless) stuff in the normalisation of the backwards (i.e., I simply omitted backwards[X, 0] from all normalisation. I guess this is OK, but maybe you could check that I haven't messed up, @awohns ? And also that the changes make sense, and the new methods are named sensibly (I suspect some like `expand_forwards` could do with better names)

Create a class to abstract the lower triangular L matrix

---

tests/test_functions.py
tsdate/date.py

This seems pretty clear, and obvious to merge. No tests for non-contemporaneous samples yet, though...

Only tally fixed nodes for prior if at time 0

---

tests/test_functions.py
tests/utility_functions.py

This reverts the alterations made to place the nodes in the unary_node_example in time order. It isn't a requirement of a tree seq for the nodes to be in time order, so we should be able to deal with it without outputting the wrong error message. It's probably worth reverting the changes as it's a better test of whether dangling & unary nodes are properly detected (which now, I hope they are)

Revert unneeded node time change

---

tests/test_functions.py
tsdate/date.py

Fixes #124 - I think we should simply merge this, since all tests pass. Then I can get on with replumbing the NodeGridPrior class, which will allow us to deal with noncontemporaneous samples properly.

Remove noncontemporaneous samples from prior

---

tests/test_functions.py
tests/test_inference.py
tests/utility_functions.py
tsdate/date.py

This only issues a warning (rather than raising an error) if we attempt to calculate a prior with dangling nodes. The prior is then set to NaN for a dangling node, which should be fine.
It's now only when we try to run the Inside algo that we fail on a dangling node. I think this is the correct way to do it.

Use ts from likelihood class, and allow dangling nodes in prior only

---

tests/test_functions.py
tests/test_inference.py
tests/utility_functions.py
tsdate/prior.py

One line change to support the tree sequences that result from a call to keep_intervals() or delete_intervals().
Tests to show that the priors are unchanged.
NOTE: the resulting date estimates will be different with _any_ deletion of an internal interval. The test "test_intervals()" in tests/test_inference.py() demonstrates this. If we take an internal interval in the two_tree_ts_extra_long() of [0.5, 1.0], the resulting dates will be different than the results of tsdate on two_tree_ts(). I think this is expected.

Support for keep_intervals and delete_intervals

---

tests/test_functions.py
tests/test_inference.py
tests/utility_functions.py
tsdate/date.py

As mentioned in #100, constrain_ages_topo is very slow. This PR has a new implementation with is much faster. A number of tests are included.

Faster method for constrain_age_topo with tests

---

tests/test_cli.py
tests/test_functions.py
tests/test_inference.py
tsdate/date.py

Unconstrained node age estimates are lost with the output of `tsdate.date()`. The solution here is to keep the mean and variance of node age in the metadata of each node.
Note, this will only affect trees dated using the inside-outside method, as the node ages are already consistent with the outside-maximization approach.

Add unconstrained metadata to nodes

---

docs/index.rst
docs/tutorial.rst
tests/test_cli.py
tests/test_functions.py
tests/test_inference.py
tests/utility_functions.py
tsdate/__init__.py
tsdate/base.py
tsdate/date.py
tsdate/util.py

Adds two functions to support the inference of tree sequences from modern and ancient samples. The first is `sites_time`: a function to retrieve the times associated with each variable site, optionally using the unconstrained age estimates from the Inside-Outside algorithm of `tsdate`. The second function is `add_sites_time`: a wrapper for a few `tsinfer` and `tsdate` functions which adds ages to the SampleData.sites_time Zarr array. 
Also adds a tutorial which shows how to perform such inference.

Support for ancient samples

---

docs/tutorial.rst

I think we had decided to use "historical" (with the additional "al"), even though it is longer. Either way, we should be consistent about it!

Change "historic" to "historical"

---

docs/conf.py

This is the "new" way to do things, apparently. I need this to get the docs to compile on my machine.

Newer autodoc_mock_imports syntax

---

requirements.txt
tests/test_functions.py
tests/utility_functions.py
tsdate/prior.py
tsdate/util.py

Removes our `tree_num_children()` function and use `tskit.Tree.num_children()` instead

Use tskit num_children() method

---

tsdate/date.py

Adds a `logging.info` call if `constrain_ages_topo` changes node times.
Resolves #82 
@hyanwong, we don't need to test logging do we?

logging when constrain ages changes node time

---

tests/test_functions.py
tests/utility_functions.py
tsdate/util.py

A fair bit of documentation change, and some other changes as discussed on slack. In particular, the parameter name has changed from mutation_age to node_selection, ignore_multiallelic has been removed, nodes_time now only gets unconstrained times (and the logic is moved into  sites_time_from_ts), and the epsilon value is renamed min_time and set to default to 1 for *all* zero-time sites. This means setting min_time=0 in lots of the unit tests, but I think that's OK.

Changes to sites_time_from_ts

---

tests/test_cli.py
tests/test_functions.py
tests/test_inference.py
tsdate/date.py

Bleeding-edge version of `msprime` includes mutation times. When we date a simulated tree sequence, we often set the child node of a mutation to be older than the mutation itself, which causes `tskit` to complain.
Simple fix is to set all mutation times to `tskit.UNKNOWN_TIME` and add a note in the documentation of `tsdate.date()`.
A test that mutation times are removed is skipped until `msprime` 1.0 has been released.

Fix msprime compatibility

---

tests/test_cache.py

[A test ](https://github.com/tskit-dev/tsdate/blob/2f5821a6ba5ba3a53c91aff0ff680059ac8aab63/tests/test_cache.py#L28) to check the existence of a cache fails if `tests/test_cache.py` is not the first tests module to be run. This changes the test to delete the cache if it is found.

fix cache test

---

.circleci/config.yml
tests/test_cache.py
tsdate/cache.py

A race condition can cause problems with the tests of the cache. `test_cache.test_cached_prior()` checks that the cache does not exist, while `test_cache.test_cache_dir_exists` fails if the cache dir already exists.
Easy fix is to just remove parallel pytests, I think better solution is to change the way we cache

fix race condition tests

---

tsdate/cache.py

There's an unnecessary print statement if the cache already exists. Replace it with logging (as before)

Remove print statement when cache exists

---

tsdate/cache.py

A race condition can occur when testing the cache (removing and making the directory), so we use a "try except" block instead of an "if cache exists"

fix race condition, again

---

tsdate/date.py

For some reason we use `len(self.ts.tables.nodes.time[self.ts.tables.edges.child[:]])` rather than simply self.ts.num_edges

Use num_edges directly

---

tsdate/__init__.py

Makes `tsdate.get_dates` available so people can look at the marginal posterior distributions on node time. Won't document it for now.

Export get_dates (without documentation)

---

requirements.txt
tsdate/core.py

Resolves the performance issue noted in #174 by removing `numba.typed.List` and using reflect lists instead, pinning the numba version to avoid the deprecation issue (for now)

remove typed list and pin numba

---

tests/test_cache.py
tests/test_functions.py
tests/test_inference.py
tsdate/core.py
tsdate/prior.py

Remove "Ne" from likelihood calculations and only use it in the prior. Doesn't affect output at all.
Look good @hyanwong ?

Use Unscaled Time Internally

---

tsdate/core.py
tsdate/provenance.py
tsdate/util.py

At the moment in tsdate we do a lot of operations where we turn everything into a tree sequence, then back into tables for editing, then back into a tree sequence, etc. It seems simpler and more efficient to keep everything as a table collection while we are simplifying, adding provenance, etc, then exporting the tree sequence right at the end.
This should also make addressing #190 easier.

Modify tables

---

tests/test_functions.py
tests/test_inference.py
tsdate/cli.py
tsdate/core.py
tsdate/prior.py

To prevent users from inadvertently running `tsdate` without a mutation rate or using an unsimplified tree sequence from `tsinfer`, this PR makes `mutation_rate` are required parameter and fails if the tree sequence is unsimplified

require mutation_rate, fail if unsimplified

---

tests/test_functions.py
tsdate/core.py

As we can get them from posterior.timepoints directly, which is more reliable anyway.

No need to pass timepoints to posterior_mean_var

---

CHANGELOG.rst
tests/test_functions.py
tests/test_inference.py
tsdate/base.py
tsdate/core.py

Previously we claimed to return posteriors that were probabilities but the testing was broken, so we didn't notice that we weren't scaling the posteriors to add up to one (i.e. they weren't actually probabilities). This fixes the problem, but therefore changes the posteriors that are output. I think this is the right thing to do.

Fix unit test and posteriors

---

tests/test_functions.py
tsdate/prior.py

With #248, if a user-specified set of timepoints was provided to `build_grid`, these were assumed to be on a coalescent time scale. With this fix, user-supplied timegrids are assumed to be on a generational scale instead (as was the case pre-#248).

Fixup for #248, use generational scale for custom time grid

---

requirements.txt
tests/distribution_functions.py
tests/test_approximations.py
tests/test_functions.py
tests/test_hypergeo.py
tests/test_inference.py
tsdate/approx.py
tsdate/base.py
tsdate/core.py
tsdate/demography.py
tsdate/hypergeo.py
tsdate/prior.py

WIP
- Doesn't use a time discretization -- instead, each node has two variational parameters (shape/rate of gamma) for each of inside/outside/posterior
- The core idea is to approximate convolution likelihoods by "quasi-Poisson-like" functions. Then the updates are just summations of sufficient statistics for each incoming edge at each node.
- There's no numerical convolution required -- instead, everything is done with Laplace transforms (this requires evaluating hypergeometric functions, added `mpmath` as a dependency to do this as it seems to be much more stable numerically than `scipy`'s implementations)
- Some incoming features will be trickier to implement than for the discretized case (ancient samples, variable population size), but will still be possible I think

Gamma-variational inference scheme

---

CHANGELOG.rst
tests/test_functions.py
tests/test_provenance.py
tsdate/core.py
tsdate/demography.py
tsdate/provenance.py
tsdate/util.py

A few stacked up changes here. Nothing terribly changes, though: mainly extra testing

Provenance saving

---

tests/test_hypergeo.py
tsdate/approx.py
tsdate/hypergeo.py

- Remove some unnecessary asserts that cause EP to error out
- Add a better check for catastrophic cancellation when using `_hyp2f1_dlmf1583` and the hypergeometric function is close to singular
- Make check for 2F1 convergence a bit more stringent (should probably make tolerance settable, when we have a control dict)
- Add a couple tests that cancellation is handled correctly
- Should fix #286 and #289

Numerical fixes (closes #286 and #289)

---

tests/test_functions.py
tests/test_priors.py
tsdate/prior.py

And implement (but don't use) a log-span weighting option for mixture priors. See https://github.com/tskit-dev/tsdate/issues/292#issuecomment-1633112244

Expose node spans not weights

---

tests/test_approximations.py
tests/test_hypergeo.py
tsdate/approx.py
tsdate/core.py
tsdate/hypergeo.py

- A bit better handling of cancellation error in custom 2F1
- Use high-precision mpmath.hyp2f1 to match mean and variance as a failsafe
- Project approximations with large shape parameters (threshold set by `max_shape`) to a predetermined value of the shape parameter. 
The cap on the shape parameter basically says, "this approximation is extremely precise, but we'll only let it get *this* precise so that the distribution doesn't degenerate". This is akin to setting a minimum variance, except that the shape parameterization is scale invariant. By default, `max_shape` should be None, because if the shape parameters do get extremely large (e.g. the approximation degenerates) then that tells us that there's some inconsistency in the topology that makes dating difficult. For example, this can …

Numeric fixes for extremely large shape parameters

---

tsdate/core.py

Fix minor bug where unmapped mutations are assigned to the last edge by `Likelihoods`, causing a single large outlier when dating

Fix excess mutation count at last edge (closes #308)

---

tests/test_functions.py
tests/test_inference.py
tsdate/core.py

- Rationale in #249, first step in addressing #237
- `get_dates` has an extra output at the end, which is the marginal likelihood from the inside pass
- This is returned by `date` if `return_likelihood = True`, in a way that's similar to what is done for posteriors
- The only change to the existing algorithm is to keep the Poisson likelihoods unstandardized. This change doesn't seem to increase the risk of over/underflow, given that inside values are standardized at each node.

Return marginal likelihood from inside algorithm

---

tests/utility_functions.py

Example is now unary and should fix the issue in https://github.com/tskit-dev/tsdate/pull/321

Explicitly defined multiroot example tree

---

tests/test_cli.py
tests/test_inference.py
tests/test_provenance.py
tsdate/core.py

Fixes #327 and also stores the method and time units in the provenance

Minor fixes to core.py

---

tests/test_cache.py
tests/test_cli.py
tests/test_functions.py
tests/test_priors.py
tests/utility_functions.py
tsdate/core.py
tsdate/demography.py
tsdate/prior.py

Use a recursive approach to calculating prior variances that is a couple of orders of magnitude faster:
so it's possible to get the exact variances for 100,000 tips in a few minutes (by comparison, it's infeasible to get exact variances for more than 2,000 tips or so with the original algorithm). 
Some indication that the two algorithms are equivalent, showing sqrt(variance) for 1280 tips:
Still trying to get my head around the interpolation scheme used for the approximation, and if this algorithm will be useful there (it recurses backwards from the maximum number of tips).

Faster prior variance calculation

---

tsdate/base.py
tsdate/cli.py
tsdate/core.py
tsdate/prior.py

Previously the numbers in prior.py and core.py did not match, so warnings were output unnecessarily

Set number for approx using a constant

---

docs/introduction.md
docs/methods.md
docs/priors.md
docs/usage.md
docs/variable_popsize.md
tsdate/__init__.py

Some suggested changes to the docs wrt the variational gamma method.

Docs proofread

---

CHANGELOG.md
tests/test_approximations.py
tests/test_functions.py
tests/test_hypergeo.py
tsdate/approx.py
tsdate/core.py
tsdate/demography.py
tsdate/hypergeo.py
tsdate/prior.py

We've been having issues (eg #322, #323) using tsdate on realistic datasets where the EP updates fail, because the cavity distributions are degenerate. This often occurs in the early iterations, and happens when there's a lot of "movement" in the approximate posteriors (e.g. many updates that substantially shift the approximations). This is a common problem with EP, and the solution is to use damping: when forming the cavity distributions, we only subtract out a fraction of the message. We choose this fraction to be as large as possible while still keeping the cavity distributions proper. This is somewhat akin to step-size selection in quasi-Newton/gradient descent. A good overview of the strategy is [here](https://tminka.github.io/papers/minka-power-ep.pdf).
To make this work required …

Fix numerical issues via damping

---

requirements.txt
tests/test_hypergeo.py
tests/test_inference.py
tsdate/approx.py
tsdate/core.py
tsdate/hypergeo.py

This adds (or rather documents) an option `min_kl`, which if set to False matches central moments rather than sufficient statistics. This is around 2-3 times faster, but introduces some upward bias in the ages of very young nodes.

Minor fixes for central moment matching

---

CHANGELOG.md
docs/priors.md
docs/python-api.md
docs/usage.md
tests/test_functions.py
tests/test_inference.py
tsdate/__init__.py
tsdate/cli.py
tsdate/core.py
tsdate/prior.py

- Make `get_dates` and `variational_dates` part of the public API, that will return unconstrained node ages and posteriors. Rename `get_dates` to `discretised_dates`. The main method `date` calls one of these functions and inserts constrained dates into the tree sequence.
- Moves docstrings for method specific arguments into `discretised_dates` and `variational_dates`. Shared arguments are documented in `date`.
- In the docstrings, the posteriors from the inside-outside algo are referred to as being over 'time slices'. This isn't really correct, the likelihood is evaluated at fixed time points rather than integrated over a time interval. So have changed docstrings accordingly. (It's a little confusing because the default prior is calculated over intervals from a CDF, but given that …

Refactor/redocument API

---

docs/python-api.md
requirements.txt
setup.cfg
tests/test_functions.py
tests/test_inference.py
tests/test_provenance.py
tsdate/__init__.py
tsdate/base.py
tsdate/cli.py
tsdate/core.py
tsdate/prior.py

Make `tsdate.date()` a wrapper for `tsdate.inside_outside()`, `tsdate.variational_gamma()`, or `tsdate.maximization()`. This allows easier documentation and reuse, and is a follow-up to #350 
Also ban `tsdate.maximization()` from using the `return_posteriors` parameter.

Api extras

---

tests/test_inference.py
tsdate/cli.py
tsdate/core.py
tsdate/mixture.py
tsdate/prior.py

1. To use the coalescent prior to initialize a mixture with `K` components, pass `prior_mixture_dim=K`
2. To disable the EM updates of the mixture components, pass `em_iterations=0`
3. The "original" global prior for the variational gamma method can be used via `prior_mixture_dim=1, em_iterations=0`
4. The default is to optimize a single component prior (`prior_mixture_dim=1, em_iterations=10`)

Add mixture-of-gammas global prior, updated by EM

---

docs/usage.md

and add note about estimating Ne

Update docs for posterior

---

CHANGELOG.md
tests/test_functions.py
tests/test_util.py
tsdate/constants.py
tsdate/util.py

And add split_nodes to preprocess_ts. Fixes #373

Save flags and metadata when splitting disjoint nodes

---

CHANGELOG.md
docs/introduction.md
docs/methods.md
docs/popsize.md
docs/priors.md
docs/usage.md

as we actually do use a "prior" (really, regularisation) on root node ages.

Fix references to "flat" priors in docs

---

docs/usage.md
tests/test_inference.py
tsdate/core.py
tsdate/variational.py

Just add an extra "allow_unary" flag to all the methods. You mentioned it could be undocumented @nspope , but actually it seems perfectly OK to document this. I can't imagine the API would change at all.

Allow unary nodes

---

requirements.txt
tests/test_provenance.py
tsdate/core.py
tsdate/provenance.py
tsdate/util.py

This should make it easier to create perf plots, etc.
The max_memory usage requirements may not be very reliable, when e.g. the `date()` method is called within a single script.

Record resources used in tsdate inference

---

tests/test_accuracy.py
tests/test_inference.py
tsdate/core.py

Fixes #302. As described in that issue, we issue a warning and don't write metadata for old tsinfer versions (these have no schema, and raw byte metadata in the nodes table)

Add `set_metadata` parameter

---

CHANGELOG.md
docs/installation.md
tests/exact_moments.py
tests/test_hypergeo.py
tsdate/accelerate.py
tsdate/approx.py
tsdate/discrete.py
tsdate/hypergeo.py
tsdate/phasing.py
tsdate/prior.py
tsdate/rescaling.py
tsdate/util.py
tsdate/variational.py

Allow the numba cache to be used, for development

---

tests/test_noncontemporary.py
tsdate/approx.py
tsdate/core.py
tsdate/rescaling.py
tsdate/util.py
tsdate/variational.py

A minimal case:
```python
Mutations: 16
--- TRUE TREES ---
13.00┊               ┊             ┊             ┊       16    ┊
┊               ┊             ┊             ┊     ┏━━┻━━┓ ┊
12.00┊  15           ┊      15     ┊             ┊     ┃     ┃ ┊
┊ ┏━┻━━┓        ┊   ┏━━━┻━━┓  ┊             ┊     ┃     ┃ ┊
8.00 ┊ ┃    ┃        ┊  13      ┃  ┊    13       ┊    14     ┃ ┊
┊ ┃    ┃        ┊ ┏━┻━┓    ┃  ┊ ┏━━┳┻━━━┓   ┊  ┏━━┻━┓   ┃ ┊
7.00 ┊ ┃   11        ┊ ┃   ┃   11  ┊ ┃ 11    ┃   ┊ 12    ┃   ┃ ┊
┊ ┃ ┏━┳┻━━┓     ┊ ┃   ┃   ┏┻┓ ┊ ┃ ┏┻┓   ┃   ┊ ┏┻┓   ┃   ┃ ┊
6.00 ┊ 1 2 3   0     ┊ 2   1   3 0 ┊ 2 3 0   1   ┊ 2 0   1   3 ┊
┊         ┃     ┊     ┃     ┃ ┊     ┃   ┃   ┊   ┃   ┃     ┊
3.00 ┊        10     ┊     ┃     ┃ ┊     ┃   ┃   ┊   ┃   ┃     ┊
┊       ┏━┻━┓   ┊     ┃     ┃ ┊     ┃   ┃   ┊   ┃ …
```

Allow internal/non-contemporary samples for dating sc2ts, pedigrees

---

CHANGELOG.md
docs/references.bib
tests/test_cli.py
tests/test_functions.py
tests/test_inference.py
tsdate/core.py
tsdate/util.py
tsdate/variational.py

Fixes a problem when we have multiple mutations at the same site on the same edge (can't put them halfway between edge parent and edge child).

replace constrain_mutations with the built in `compute_mutation_times`

---

docs/_toc.yml
docs/citation.md
docs/index.md

separate citation documentation in a separate file.
This is done to display and reference the citation file in the common citation page for tskit-dev: https://tskit.dev/citation/

separate citation documentation into citation.md
